# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_add_new_not_null_field_preserve_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a',
            name='new_not_null_field_preserve_default',
        ),
    ]
