# Generated by Django 2.0.1 on 2018-01-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='big_int',
            field=models.BigIntegerField(null=True),
        ),
    ]
