# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_add_lots_of_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='a',
            unique_together=set([('null_field', 'new_not_null_field')]),
        ),
    ]
