# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_add_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='a',
            unique_together=set([]),
        ),
    ]
