# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_drop_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mya', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.A')),
                ('myafk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_a', to='test_app.A')),
                ('myafkprotect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_a', to='test_app.A')),
                ('myaname', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thenewclass', to='test_app.A')),
            ],
        ),
        migrations.AddField(
            model_name='a',
            name='mynewclass',
            field=models.ManyToManyField(to='test_app.NewClass'),
        ),
    ]
