# Generated by Django 2.0.1 on 2018-01-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_add_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
    ]
