# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_add_table_with_relations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newclass',
            name='myafkprotect',
        ),
        migrations.AlterField(
            model_name='newclass',
            name='myaname',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thenewclass', to='test_app.A'),
        ),
    ]
