# Generated by Django 2.0.1 on 2018-01-21 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_add_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='current_date',
            field=models.DateField(default=datetime.date(2018, 1, 21)),
        ),
    ]
