# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_rename_and_drop_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='new_not_null_field',
            field=models.IntegerField(db_index=True),
        ),
    ]
