# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0010_add_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='new_not_null_field',
            field=models.IntegerField(),
        ),
    ]
