# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_drop_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('null_field', models.IntegerField(null=True)),
                ('new_not_null_field', models.IntegerField()),
                ('mybinary', models.BinaryField(null=True)),
                ('myboolean', models.BooleanField(default=False)),
                ('mychar', models.CharField(max_length=256, null=True)),
                ('mydate', models.DateField()),
                ('mydecimal', models.DecimalField(decimal_places=5, max_digits=20, null=True)),
                ('myduration', models.DurationField(null=True)),
                ('myemail', models.EmailField(max_length=254, null=True)),
                ('myfile', models.FileField(null=True, upload_to=b'')),
                ('myfilepath', models.FilePathField(null=True)),
                ('myfloat', models.FloatField(null=True)),
                ('myimage', models.ImageField(null=True, upload_to=b'')),
                ('mybiginteger', models.BigIntegerField(null=True)),
                ('mygenericipaddress', models.GenericIPAddressField()),
                ('mynullboolean', models.NullBooleanField()),
                ('mypositiveinteger', models.PositiveIntegerField(default=5)),
                ('mypositivesmallinteger', models.PositiveSmallIntegerField(null=True)),
                ('myslug', models.SlugField(null=True)),
                ('mytext', models.TextField(unique=True)),
                ('mytime', models.TimeField()),
                ('myuuid', models.UUIDField(null=True, unique=True)),
                ('myurl', models.URLField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='a',
            name='mynewclass',
        ),
        migrations.RemoveField(
            model_name='newclass',
            name='mya',
        ),
        migrations.RemoveField(
            model_name='newclass',
            name='myafk',
        ),
        migrations.RemoveField(
            model_name='newclass',
            name='myaname',
        ),
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='NewClass',
        ),
    ]
