# Generated by Django 2.0.1 on 2018-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0011_add_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='dec',
            field=models.DecimalField(decimal_places=20, max_digits=30, null=True),
        ),
    ]
