# Generated by Django 2.0.1 on 2018-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0012_add_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='elapsed',
            field=models.DurationField(null=True),
        ),
    ]
