# Generated by Django 2.0.1 on 2018-01-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0013_add_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='mail',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
    ]
