# Generated by Django 2.0.1 on 2018-01-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0014_add_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='attachments',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
