# Generated by Django 2.0.1 on 2018-01-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0016_add_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='floating',
            field=models.FloatField(default=0.0),
        ),
    ]
