# Generated by Django 2.0.1 on 2018-01-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0017_add_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='generic_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
