# Generated by Django 2.0.1 on 2018-01-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0018_add_generic_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='null_bool',
            field=models.NullBooleanField(),
        ),
    ]
