# Generated by Django 2.0.1 on 2018-01-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0019_add_null_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='positive_int',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
