# Generated by Django 2.0.1 on 2018-01-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0020_add_positive_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='small_pos_int',
            field=models.PositiveSmallIntegerField(default=1234),
        ),
    ]
