# Generated by Django 2.0.1 on 2018-01-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0023_add_small_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='texty',
            field=models.TextField(null=True),
        ),
    ]
