# Generated by Django 2.0.1 on 2018-01-21 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0024_add_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='time',
            field=models.TimeField(default=datetime.time(18, 7)),
        ),
    ]
