# Generated by Django 2.0.1 on 2018-01-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0025_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondobject',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
