# Generated by Django 2.0.1 on 2018-02-04 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0028_add_float_with_default'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='secondobject',
            unique_together={('big_int', 'floating')},
        ),
    ]
