# Generated by Django 2.0.1 on 2018-02-04 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0034_drop_unique_on_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondobject',
            name='current_date',
            field=models.DateField(default=datetime.date(2018, 1, 21), unique_for_date=True),
        ),
    ]
