# Generated by Django 2.0.1 on 2018-02-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0036_drop_unique_for_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdObject',
            fields=[
                ('other_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
