# Generated by Django 2.0.1 on 2018-02-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0039_rename_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtherObject',
        ),
    ]
