# Generated by Django 2.0.1 on 2018-02-04 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0045_add_fk_do_nothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstobject',
            name='one2one',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='test_app.SecondObject'),
        ),
    ]
