sudo: false
language: python

services:
  - mysql
  - postgresql

before_script:
  - mysql -e 'CREATE DATABASE fake_db;'
  - psql -c 'create database fake_db;' -U postgres

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-django111

    - python: 3.4
      env: TOXENV=py34-django111
    - python: 3.4
      env: TOXENV=py34-django20

    - python: 3.5
      env: TOXENV=py35-django111
    - python: 3.5
      env: TOXENV=py35-django20

    - python: 3.6
      env: TOXENV=py36-django111
    - python: 3.6
      env: TOXENV=py36-django20

    - python: 3.6
      env: TOXENV=lint

install:
  - pip install tox

script:
  - tox
